### ISSUE TITLE
Path de instalación de MIPS ELF en el IDE

### ISSUE THREAD

**Issue by pdvelez** [AngelTerrones/MUSB#1]
Debe existir instrucciones en la instalación de Mentor Graphics Sourcery CodeBench Lite for MIPS ELF debido a que el IDE lo busca en un directorio que no es el que el instalador lo coloca por defecto. El IDE busca en: /opt/sourcery/ mientras que el instalador sugiere un path /mgc/embedded/codebench/

Solo es posible darse cuenta al momento de ejecutar "View Assembler" en el IDE.

**Comment by AngelTerrones** [comment]
Mmm, eso es raro. Por defecto ese campo debe estar vacio la primera vez que se compila/ejecuta el programa. Y esa ruta no se guarda en el proyecto.

Pregunta: ¿Estás usando el makefile ya generado por un ejemplo? Si es así, hay que regenerar desde el IDE abriendo "Project Settings" y guardando.

Agregaré una opción para actualizar automaticamente el makefile.

**Comment by pdvelez** [comment]
Posiblemente ese fue el problema, utilicé uno de los ejemplos que preparaste y generó ese error. Luego volví a instalar el ELF en la ruta /opt/sourcery/ por lo que no podría verificar si regenerarlo lo arreglaría.
