### ISSUE TITLE
Error en "View Assembler" 

### ISSUE THREAD

**Issue by pdvelez** [AngelTerrones/MUSB#2]
Al tratar de ver el código assembler del proyecto TestC obtengo el error que antes no existía:

```
[09:44:26 am] MIPS IDE: Error: make: /gcc: Command not found
make: *** [out/main.s] Error 127
```

Para descartar que fue algún archivo que quedó, creé un nuevo proyecto y copié el contenido del main.c de TestC al nuevo y el error persiste. Esto surge a partir de actualizar el repositorio con las modificaciones recientes.

Es posible que se encuentra en esta línea?:

```
MIPS_CC      = $(MIPS_BIN)/$(MIPS_PREFIX)gcc
```

Al realizar el cambio a:

```
MIPS_CC      = $(MIPS_PREFIX)gcc
```

Obtengo el error:

```
[09:50:17 am] MIPS IDE: Error: gcc: error: unrecognized option ‘-EL’
gcc: error: unrecognized option ‘-G0’
make: *** [out/main.s] Error 1
```

**Comment by AngelTerrones** [comment]
Raro.

Windows? Linux?
Path del Gcc?

**Comment by pdvelez** [comment]
Me faltó configurar los parámetros del compilador del IDE en File -> Settings: Compiler . Todo parece funcionar bien.
